module.exports = {
  RECEIVE_GAME_ROOM: 'RECEIVE_GAME_ROOM',
  REQUEST_GAME_ROOM: 'REQUEST_GAME_ROOM',

  REQUEST_RANDOM_ROOM: 'REQUEST_RANDOM_ROOM',
  RECEIVE_RANDOM_ROOM: 'RECEIVE_RANDOM_ROOM',
  REQUEST_OWN_ROOM: 'REQUEST_OWN_ROOM',
  RECEIVE_OWN_ROOM: 'RECEIVE_OWN_ROOM',
  CHOOSE_PLAYER_TYPE: 'CHOOSE_PLAYER_TYPE',

  JOIN_RANDOM_GAME: 'JOIN_RANDOM_GAME',
  JOIN_OWN_GAME: 'JOIN_OWN_GAME',

  CLOSE_RANDOM_GAME: 'CLOSE_RANDOM_GAME',
  CLOSE_OWN_GAME: 'CLOSE_OWN_GAME',

  DELETE_OWN_ROOM: 'DELETE_OWN_ROOM',

  REQUEST_CHECK_ROOM: 'REQUEST_CHECK_ROOM',
  RECEIVE_CHECK_ROOM: 'RECEIVE_CHECK_ROOM',

  DISABLE_GAME: 'DISABLE_GAME',

  ALL_PLAYERS_CONNECTED: 'ALL_PLAYERS_CONNECTED',

  LEAVE_ROOM: 'LEAVE_ROOM',
  OPPONENT_LEFT: 'OPPONENT_LEFT',
  OPPONENT_HAS_WON: 'OPPONENT_HAS_WON',
  USER_HAS_WON: 'USER_HAS_WON',

  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',

  USERS_TURN: 'USERS_TURN',
  SEND_SHOOT: 'SEND_SHOOT',
  RECEIVE_SHOOT: 'RECEIVE_SHOOT',
  SEND_SHOOT_FEEDBACK: 'SEND_SHOOT_FEEDBACK',
  RECEIVE_SHOOT_FEEDBACK: 'RECEIVE_SHOOT_FEEDBACK',
  SEND_DESTROYED_SHIP: 'SEND_DESTROYED_SHIP',
  RECEIVE_DESTROYED_SHIP: 'RECEIVE_DESTROYED_SHIP',
  RECEIVE_GAME_ROLE: 'RECEIVE_GAME_ROLE',
  REQUEST_GAME_ROLE: 'REQUEST_GAME_ROLE',
  RECEIVE_GAME_DATA: 'RECEIVE_GAME_DATA',
  REQUEST_GAME_DATA: 'REQUEST_GAME_DATA',
  GET_GAME_DATA: 'GET_GAME_DATA',
  POST_GAME_DATA: 'POST_GAME_DATA',
};
